
import { faCloud,faSun,faCloudSun,faCloudShowersHeavy,faCloudSunRain, faSmog, faSnowflake, faCloudBolt, IconDefinition } from '@fortawesome/free-solid-svg-icons';

export const Icon_map = new Map<number,IconDefinition>([
    [0,faSun],
    [1,faSun],
    [2,faCloudSun],
    [3,faCloud],
    [45,faSmog],
    [48,faSmog],
    [51,faCloudShowersHeavy],
    [53,faCloudShowersHeavy],
    [55,faCloudShowersHeavy],
    [56,faCloudShowersHeavy],
    [57,faCloudShowersHeavy],
    [61,faCloudShowersHeavy],
    [63,faCloudShowersHeavy],
    [65,faCloudShowersHeavy],
    [66,faCloudShowersHeavy],
    [67,faCloudShowersHeavy],
    [71,faSnowflake],
    [73,faSnowflake],
    [75,faSnowflake],
    [77,faSnowflake],
    [80,faCloudShowersHeavy],
    [81,faCloudShowersHeavy],
    [82,faCloudShowersHeavy],
    [85,faSnowflake],
    [86,faSnowflake],
    [95,faCloudBolt],
    [96,faCloudBolt],
    [99,faCloudBolt],

])
// [0,faSun],
// [1,faSun],
// [2,faCloudSun],
// [3,faCloud],
// [45,faSmog],
// [48,faSmog],
// [51,faRain],
// [53,faRain],
// [55,faRain],
// [56,faRain],
// [57,faRain],
// [61,faRain],
// [63,faRain],
// [65,faRain],
// [66,faRain],
// [67,faRain],
// [71,faSnowflake],
// [73,faSnowflake],
// [75,faSnowflake"],
// [77,faSnowflake"],
// [80,faRain"],
// [81,"faRain"],
// [82,"faRain"],
// [85,"faSnowflake"],
// [86,"faSnowflake"],
// [95,"faCloudBolt"],
// [96,"faCloudBolt"],
// [99,"faCloudBolt"],